# Generated by Django 5.1.15 on 2026-06-09 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(db_column='volunteer_id', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routes',
                'indexes': [models.Index(fields=['volunteer'], name='idx_route_volunteer'), models.Index(fields=['volunteer', 'route_date'], name='idx_route_vol_date'), models.Index(fields=['route_date'], name='idx_route_date')],
            },
        ),
    ]
