# Generated by Django 5.1.15 on 2026-06-08 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_allergies_user_diet_preferences'),
        ('delivery', '0001_initial'),
        ('planning', '0003_mealplan_warnings_acknowledged_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('fresh', 'Fresh'), ('frozen', 'Frozen')], default='fresh', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('photo', models.URLField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_plan', models.ForeignKey(db_column='meal_plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='planning.mealplan')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.PROTECT, related_name='received_deliveries', to=settings.AUTH_USER_MODEL)),
                ('member_address', models.ForeignKey(db_column='member_address_id', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='accounts.address')),
                ('route', models.ForeignKey(blank=True, db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.route')),
                ('volunteer', models.ForeignKey(db_column='volunteer_id', on_delete=django.db.models.deletion.PROTECT, related_name='delivered_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliveries',
                'indexes': [models.Index(fields=['route'], name='idx_del_route'), models.Index(fields=['meal_plan'], name='idx_del_plan'), models.Index(fields=['member'], name='idx_del_member'), models.Index(fields=['member', 'scheduled_date'], name='idx_del_member_date'), models.Index(fields=['scheduled_date', 'status'], name='idx_del_date_status')],
            },
        ),
    ]
