# Generated by Django 5.1.15 on 2026-06-08 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(blank=True, null=True)),
                ('delivery', models.OneToOneField(db_column='delivery_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='delivery.delivery')),
            ],
            options={
                'db_table': 'delivery_feedback',
                'constraints': [models.UniqueConstraint(fields=('delivery',), name='uq_feedback_delivery')],
            },
        ),
    ]
