# Generated by Django 5.1.15 on 2026-06-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
