# Generated by Django 5.1.15 on 2026-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('charity', 'Charity'), ('restaurant', 'Restaurant'), ('supplier', 'Supplier'), ('corporate', 'Corporate')], max_length=20)),
            ],
            options={
                'db_table': 'partners',
                'ordering': ('legal_name',),
            },
        ),
    ]
