# Generated by Django 5.1.15 on 2026-06-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.BigIntegerField(blank=True, null=True)),
                ('amount_cents', models.BigIntegerField()),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('paypal', 'PayPal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ('donor_email', models.EmailField(max_length=254)),
                ('is_recurring', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=191, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.campaign')),
            ],
            options={
                'db_table': 'donations',
                'indexes': [models.Index(fields=['donor_id'], name='idx_don_donor'), models.Index(fields=['campaign', 'status'], name='idx_don_campaign_status'), models.Index(fields=['donor_email'], name='idx_don_email')],
            },
        ),
    ]
