# Generated by Django 5.1.15 on 2026-06-08 20:15

from django.db import migrations, models

import apps.donations.models.tokens


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(default=apps.donations.models.tokens._generate_token_id, max_length=64, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donation_magic_link_tokens',
            },
        ),
    ]
