# Generated by Django 5.1.15 on 2026-06-08 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'cities',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='partner_id',
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='partners.partner'),
        ),
        migrations.CreateModel(
            name='CaregiverLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('nurse', 'Nurse'), ('social_worker', 'Social worker'), ('other', 'Other')], max_length=20)),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links_as_caregiver', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links_as_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_caregivers',
                'constraints': [models.UniqueConstraint(fields=('member', 'caregiver'), name='uq_member_caregiver')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='accounts.city')),
            ],
            options={
                'db_table': 'user_addresses',
                'indexes': [models.Index(fields=['user'], name='idx_addr_user'), models.Index(fields=['city'], name='idx_addr_city')],
            },
        ),
    ]
