# Generated by Django 5.1.15 on 2026-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_remove_user_partner_id_user_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('applying_for_other', models.BooleanField(default=False)),
                ('caregiver_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('caregiver_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('caregiver_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('family', 'Family'), ('friend', 'Friend'), ('nurse', 'Nurse'), ('social_worker', 'Social worker'), ('other', 'Other')], max_length=20, null=True)),
                ('address_label', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city_id', models.BigIntegerField(blank=True, null=True)),
                ('dietary_ids', models.JSONField(blank=True, default=list)),
                ('allergy_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
                'indexes': [models.Index(fields=['status', '-created_at'], name='application_status_2bb59d_idx'), models.Index(fields=['email'], name='application_email_7bef0d_idx')],
            },
        ),
    ]
