# Generated by Django 5.1.15 on 2026-06-08 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='password_setup_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_setup_tokens',
                'indexes': [models.Index(fields=['user', 'used_at'], name='password_se_user_id_9f4a44_idx'), models.Index(fields=['token_hash'], name='password_se_token_h_a2c58c_idx')],
            },
        ),
    ]
