# Generated by Django 5.1.15 on 2026-06-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_password_setup_tokens'),
        ('dietary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', through='dietary.UserAllergy', to='dietary.allergy'),
        ),
        migrations.AddField(
            model_name='user',
            name='diet_preferences',
            field=models.ManyToManyField(blank=True, related_name='users', through='dietary.UserDietPreference', to='dietary.dietpreference'),
        ),
    ]
