# Generated by Django 5.1.15 on 2026-06-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_allergies_user_diet_preferences'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='partner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_applications', to='partners.partner'),
        ),
    ]
