# Generated by Django 5.1.15 on 2026-06-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchens', '0004_ingredientbatch'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('storage_temp', 'Storage temperature'), ('cooking_temp', 'Cooking temperature'), ('cold_chain', 'Cold chain'), ('hygiene', 'Hygiene'), ('cleaning', 'Cleaning'), ('pest_control', 'Pest control')], max_length=20)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4)),
                ('checked_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(db_column='checked_by', on_delete=django.db.models.deletion.PROTECT, related_name='safety_checks', to=settings.AUTH_USER_MODEL)),
                ('kitchen', models.ForeignKey(db_column='kitchen_id', on_delete=django.db.models.deletion.PROTECT, related_name='safety_checks', to='kitchens.kitchen')),
                ('meal_plan', models.ForeignKey(blank=True, db_column='meal_plan_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_checks', to='planning.mealplan')),
            ],
            options={
                'db_table': 'food_safety_checks',
                'indexes': [models.Index(fields=['kitchen'], name='idx_fsc_kitchen'), models.Index(fields=['meal_plan'], name='idx_fsc_plan')],
            },
        ),
    ]
