# Generated by Django 5.1.15 on 2026-06-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        # Stub replaced by apps.planning.MealPlan (planning.0001_initial).
        # Migration kept as a state marker so food_safety.0001_initial
        # dependency chain remains intact until 0003 cleans it up.
    ]
