# Generated by Django 5.1.15 on 2026-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0007_ingredient_allergens'),
        ('meals', '0002_meal_plan_stub'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='meals', through='kitchens.MealIngredient', to='kitchens.ingredient'),
        ),
    ]
