# Generated by Django 5.1.15 on 2026-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietary', '0001_initial'),
        ('meals', '0003_meal_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='diets',
            field=models.ManyToManyField(blank=True, related_name='compatible_meals', to='dietary.dietpreference'),
        ),
    ]
