# Generated by Django 5.1.15 on 2026-06-08 14:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('partner_id', models.BigIntegerField(blank=True, null=True)),
                ('is_outsourced', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
            ],
            options={
                'db_table': 'kitchens',
                'indexes': [models.Index(fields=['partner_id'], name='kitchens_partner_a4a098_idx')],
            },
        ),
    ]
