# Generated by Django 5.1.15 on 2026-06-08 14:53

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_ingredient'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_meals', to='kitchens.ingredient')),
                ('meal', models.ForeignKey(db_column='meal_id', on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='meals.meal')),
            ],
            options={
                'db_table': 'meal_ingredients',
                'constraints': [models.UniqueConstraint(fields=('meal', 'ingredient'), name='uq_meal_ingredient')],
            },
        ),
    ]
