# Generated by Django 5.1.15 on 2026-06-08 14:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_mealingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=80, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_at', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='kitchens.ingredient')),
                ('kitchen', models.ForeignKey(db_column='kitchen_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='kitchens.kitchen')),
            ],
            options={
                'db_table': 'ingredient_batches',
                'indexes': [models.Index(fields=['ingredient'], name='idx_batch_ingredient'), models.Index(fields=['kitchen'], name='idx_batch_kitchen'), models.Index(fields=['expiration_date'], name='idx_batch_expiry')],
            },
        ),
    ]
