# Generated by Django 5.1.15 on 2026-06-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0004_ingredientbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(db_column='kitchen_id', on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alert_logs', to='kitchens.kitchen')),
            ],
            options={
                'db_table': 'expiry_alert_logs',
                'constraints': [models.UniqueConstraint(fields=('kitchen', 'sent_date'), name='uniq_alert_kitchen_day')],
            },
        ),
    ]
