# Generated by Django 5.1.15 on 2026-06-08 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0007_ingredient_allergens'),
        ('meals', '0004_meal_diets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(db_column='meal_id', on_delete=django.db.models.deletion.PROTECT, related_name='meal_ingredients', to='meals.meal'),
        ),
    ]
