# Generated by Django 5.1.15 on 2026-06-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchens', '0006_schedule_expiry_alerts'),
        ('meals', '0002_meal_plan_stub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('day_of_week', models.CharField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=3)),
                ('meal_type', models.CharField(choices=[('fresh', 'Fresh'), ('frozen', 'Frozen')], default='fresh', max_length=6)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='kitchens.kitchen')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='meals.meal')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_plans',
                'indexes': [models.Index(fields=['service_date'], name='idx_plan_date')],
                'constraints': [models.UniqueConstraint(fields=('kitchen', 'service_date'), name='uq_meal_plan_kitchen_date')],
            },
        ),
    ]
