# Generated by Django 5.1.15 on 2026-06-08 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'allergies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DietPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'diet_preferences',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(db_column='allergy_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='dietary.allergy')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='allergy_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allergy_user',
                'constraints': [models.UniqueConstraint(fields=('user', 'allergy'), name='uq_user_allergy')],
            },
        ),
        migrations.CreateModel(
            name='UserDietPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_preference', models.ForeignKey(db_column='diet_preference_id', on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='dietary.dietpreference')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='diet_preference_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diet_preference_user',
                'constraints': [models.UniqueConstraint(fields=('user', 'diet_preference'), name='uq_user_diet_preference')],
            },
        ),
    ]
